import Head from 'next/head'
import type { FC, ReactNode } from 'react'

import { Header } from './Header'

type LayoutProps = {
  children: ReactNode
}

export const Layout: FC<LayoutProps> = ({ children }) => {
  return (
    <div>
      <Head>
        <title>GW KADAI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="px-4 mx-auto w-full">{children}</main>
    </div>
  )
}
