import Head from 'next/head'

export const TopPresenter = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex">
          <p className="m-auto text-3xl font-bold underline">Hello AIKO!</p>
        </div>
      </main>
    </div>
  )
}
